# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bba5c7698f5abf1d4ef45fb05dd71f92eac9704544f17134db4a724d5b218bddcb9e086eac845d4bb6f1a052f08a1d370927284a3b32a1fe3e68b4055644308

test:
  secret_key_base: f28b0e6649646d1c3d3bcc491711a0899ca4fd07172447580e22b42651cc1fa9f2dbb5b9c21abc0d0cefcfbbec4f23556a8aaff0451ea4885c43bdcbc627c675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
